name:                megarecord
version:             0.1.0.0
synopsis:            Extensible records and Rows
homepage:            https://github.com/jvanbruegge/megarecord#readme
license:             Apache-2.0
author:              Jan van Brügge
maintainer:          supermanitu@gmail.com
copyright:           2018 Jan van Brügge
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - ghc-prim
  - first-class-families
  - aeson
  - text

executable:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - megarecord

library:
  source-dirs: src
  exposed-modules:
    - Data.Kind.Row
    - Data.Kind.RowList
    - Data.Record
    - Data.Variant
    - Data.Functor.Variant

tests:
  spec:
    main: Tests.hs
    source-dirs:
      - src
      - test
    dependencies:
      - inspection-testing
